/*
 * BREATHE NodeSim - node catalog
 *
 * Every node is a physiological concept. "in" lists the nodes it depends on
 * with the sign of the relation: '+' same direction, '-' opposite direction,
 * '±' non-monotonic (U-shaped) relation.
 * col/row give the default position in the graph.
 */
(function (global) {
	'use strict';

	const CATEGORIES = {
		vent: { label: 'Ventilatore', color: 'var(--c-vent)' },
		pat: { label: 'Paziente', color: 'var(--c-pat)' },
		mech: { label: 'Meccanica respiratoria', color: 'var(--c-mech)' },
		gas: { label: 'Scambi gassosi', color: 'var(--c-gas)' },
		hemo: { label: 'Emodinamica', color: 'var(--c-hemo)' },
		o2: { label: 'Trasporto di O₂ e metabolismo', color: 'var(--c-o2)' }
	};

	const inspSetting = o => o.mode === 'PC' ? o.pinsp : o.mode === 'CPAP' ? o.ps : o.vtSet;

	const NODES = [
		/* ------------------------------------------------ ventilator & patient */
		{ id: 'peep', cat: 'vent', col: 0, row: 0, label: 'PEEP impostata', unit: 'cmH₂O', dec: 0, key: 'peepSet', in: [],
			desc: 'Pressione positiva mantenuta dal ventilatore a fine espirazione. Mantiene aperti gli alveoli instabili ma si trasmette in parte alla pleura e quindi al cuore e ai grandi vasi.',
			formula: 'Parametro PositiveEndExpiratoryPressure di breathe.engine (data.Ventilator).' },
		{ id: 'insp', cat: 'vent', col: 0, row: 1, label: 'Target inspiratorio', unit: '', dec: 0, value: inspSetting,
			unitFn: o => o.mode === 'VC' ? 'mL' : 'cmH₂O',
			labelFn: o => o.mode === 'PC' ? 'Pinsp (PIP)' : o.mode === 'CPAP' ? 'Pressione di supporto' : 'Volume corrente impostato', in: [],
			desc: 'In volume controllato (VC) si imposta il volume corrente; in pressione controllata (PC) la pressione inspiratoria di picco; in CPAP la pressione di supporto (ΔPS). Il volume erogato dipende poi dalla meccanica.',
			formula: 'TidalVolume (VC), InspiratoryPressure (PC), DeltaPressureSupport (CPAP).' },
		{ id: 'rr', cat: 'vent', col: 0, row: 2, label: 'Frequenza respiratoria', unit: 'atti/min', dec: 0, key: 'rr', in: [],
			desc: 'Frequenza effettiva: quella impostata, oppure quella del paziente se in modalità assistita (AC) respira più velocemente. Riduce il tempo espiratorio e può causare air-trapping.',
			formula: 'FR = max(FR impostata, FR spontanea) in AC; FR spontanea = FR basale · (1 − sedazione) · (PaCO₂/40)².' },
		{ id: 'ti', cat: 'vent', col: 0, row: 3, label: 'Tempo inspiratorio', unit: 's', dec: 2, key: 'ti', in: [],
			subFn: o => 'I:E 1:' + (o.ie > 0 ? (1 / o.ie).toFixed(1) : '–'),
			desc: 'Durata dell’inspirazione. Un Ti lungo aumenta la pressione media delle vie aeree e riduce il tempo per espirare.',
			formula: 'InspiratoryPeriod; Te = 60/FR − Ti.' },
		{ id: 'fio2', cat: 'vent', col: 0, row: 4, label: 'FiO₂', unit: '%', dec: 0, value: o => o.fio2 * 100, in: [],
			desc: 'Frazione inspirata di ossigeno. Corregge l’ipossiemia da alterato rapporto V/Q, molto meno quella da shunt vero.',
			formula: 'PAO₂ = FiO₂·(760 − 47) − PaCO₂·[FiO₂ + (1 − FiO₂)/0,8]' },
		{ id: 'raw', cat: 'pat', col: 0, row: 5, label: 'Resistenze vie aeree', unit: 'cmH₂O/L/s', dec: 0, key: 'raw', in: [],
			range: { warnHi: 15, critHi: 25 },
			desc: 'Resistenza del tubo endotracheale e delle vie aeree. Aumenta con BPCO, broncocostrizione, ostruzione. Con la compliance determina la costante di tempo (τ = R·C).',
			formula: 'Raw = 9·(1 + 2,5·bronchite + 0,8·enfisema + 3·broncocostrizione) + 30·ostruzione' },
		{ id: 'ccw', cat: 'pat', col: 0, row: 6, label: 'Compliance parete toracica', unit: 'mL/cmH₂O', dec: 0, key: 'ccw', in: [['iap', '-']],
			desc: 'Distensibilità di gabbia toracica e addome. Si riduce con l’obesità (BMI). Più la parete è rigida, più pressione delle vie aeree arriva alla pleura.',
			formula: 'Ccw = 180 / (1 + 0,8·obesità), obesità = (BMI − 25)/15' },
		{ id: 'lungdz', cat: 'pat', col: 0, row: 7, label: 'Polmone reclutabile', unit: '%', dec: 0, key: 'recruitable', in: [],
			subFn: o => 'consolidato ' + o.consolidated.toFixed(0) + '%',
			desc: 'Quota di polmone collassato ma riapribile. Anche nel polmone sano in anestesia generale circa l’8% delle basi può collassare (atelettasie da anestesia); di più con ARDS, polmonite, obesità e addome teso. La quota consolidata non si riapre con la pressione.',
			formula: 'reclutabile = 8% + 22%·ARDS + 15%·polmonite + 8%·obesità + 0,6%·(IAP − 7)' },
		{ id: 'volemia', cat: 'pat', col: 0, row: 8, label: 'Volemia', unit: '%', dec: 0, key: 'volemia', in: [],
			range: { warnLo: 90, critLo: 80, warnHi: 115 },
			desc: 'Volume circolante rispetto alla norma. Determina il volume “stressato” e quindi la pressione media di riempimento sistemico: è la riserva che protegge il ritorno venoso dagli effetti della PEEP.',
			formula: 'Volemia + boli di fluidi (60% intravascolare) − perdite' },
		{ id: 'contract', cat: 'pat', col: 0, row: 9, label: 'Contrattilità VS', unit: '%', dec: 0, key: 'contract', in: [],
			range: { warnLo: 80, critLo: 60 },
			desc: 'Funzione sistolica intrinseca. Nel cuore insufficiente la curva di Starling è piatta: la gittata dipende poco dal precarico e molto dal postcarico.',
			formula: '1 − 0,5·gravità della disfunzione sistolica' },
			{ id: 'iap', cat: 'pat', col: 0, row: 10, label: 'Pressione intra-addominale', unit: 'mmHg', dec: 0, key: 'iap', in: [],
			range: { warnHi: 12, critHi: 20 },
			desc: 'Pressione nell’addome (normale in terapia intensiva 5–7 mmHg, ipertensione da 12). Oltre 7 mmHg irrigidisce la parete toracica e alza la pressione pleurica: la PEEP si trasmette di più al torace e al cuore, le basi polmonari collassano. È il meccanismo dell’ARDS "extrapolmonare" (Gattinoni 1998).',
			formula: 'Ccw ÷ (1 + 0,05·(IAP − 7)); Ppl₀ + 0,4·(IAP − 7)' },

		/* --------------------------------------------------------- mechanics */
		{ id: 'vt', cat: 'mech', col: 1, row: 0, label: 'Volume corrente erogato', unit: 'mL', dec: 0, key: 'vt',
			subFn: o => o.vtKg.toFixed(1) + ' mL/kg PBW', in: [['insp', '+'], ['crs', '+'], ['peeptot', '-']],
			range: { warnHi: 8.5, critHi: 10, valueFn: o => o.vtKg },
			desc: 'Volume effettivamente insufflato. In VC è imposto; in PC e CPAP dipende da compliance, resistenze e dalla PEEP totale (una PEEP intrinseca riduce il gradiente di pressione).',
			formula: 'PC: VT = [V(PIP) − V(PEEPtot)]·(1 − e^(−Ti/τ)).  Obiettivo protettivo: 6 mL/kg di peso ideale.' },
		{ id: 'autopeep', cat: 'mech', col: 1, row: 1, label: 'Auto-PEEP', unit: 'cmH₂O', dec: 1, key: 'autoPeep',
			in: [['rr', '+'], ['vt', '+'], ['raw', '+'], ['ti', '+']], range: { warnHi: 2, critHi: 5 },
			desc: 'PEEP intrinseca da svuotamento incompleto: se il tempo espiratorio è inferiore a ~3 costanti di tempo, il volume resta intrappolato (iperinflazione dinamica).',
			formula: 'V intrappolato = VT·e^(−Te/τ)/(1 − e^(−Te/τ));  PEEPi = V/Crs;  τ = Raw·Crs' },
		{ id: 'peeptot', cat: 'mech', col: 1, row: 2, label: 'PEEP totale', unit: 'cmH₂O', dec: 1, key: 'peepTot',
			in: [['peep', '+'], ['autopeep', '+']],
			desc: 'Pressione alveolare a fine espirazione: PEEP esterna + auto-PEEP. È quella che mantiene aperti gli alveoli e quella che grava sulla circolazione.',
			formula: 'PEEPtot = PEEPe + PEEPi' },
		{ id: 'recruit', cat: 'mech', col: 1, row: 3, label: 'Aerazione polmonare', unit: '%', dec: 0, key: 'aeration',
			subFn: o => 'reclutamento tidalico ' + o.tidalRecruit.toFixed(0) + '%', in: [['peeptot', '+'], ['pplat', '+'], ['lungdz', '-']],
			range: { warnLo: 75, critLo: 55 },
			desc: 'Frazione di polmone aerato a fine espirazione. Ha isteresi: un’unità si apre quando la pressione inspiratoria supera la sua pressione di apertura, e resta aperta solo se la PEEP supera la sua pressione di chiusura (più bassa). Per questo una manovra di reclutamento serve solo se seguita da PEEP adeguata.',
			formula: 'apertura: Φ((Pplat − Popen)/5),  chiusura: Φ((PEEPtot − Pclose)/3,5);  τ apertura 5 s/duty, τ collasso 40 s' },
		{ id: 'crs', cat: 'mech', col: 1, row: 4, label: 'Compliance statica', unit: 'mL/cmH₂O', dec: 0, key: 'crs',
			in: [['recruit', '+'], ['overdist', '-'], ['ccw', '+']], range: { warnLo: 40, critLo: 25 },
			desc: 'Distensibilità del sistema respiratorio. Nell’ARDS riflette le dimensioni del “baby lung”: aumenta se si recluta, si riduce se si sovradistende. È il criterio della titolazione decrementale della PEEP.',
			formula: 'Crs = VT / (Pplat − PEEPtot), dalla curva P-V del polmone aerato (Salazar-Knowles) + parete lineare' },
		{ id: 'pplat', cat: 'mech', col: 1, row: 5, label: 'Pressione di plateau', unit: 'cmH₂O', dec: 1, key: 'pplat',
			subFn: o => o.mode === 'SI' ? 'insufflazione sostenuta' : 'picco ' + o.ppeak.toFixed(0), in: [['peeptot', '+'], ['vt', '+'], ['crs', '-']],
			range: { warnHi: 28, critHi: 32 },
			desc: 'Pressione alveolare di fine inspirazione (a flusso zero). Limite protettivo: 30 cmH₂O.',
			formula: 'Pplat = PEEPtot + VT/Crs;  Ppicco = Pplat + Raw·Flusso' },
		{ id: 'dp', cat: 'mech', col: 1, row: 6, label: 'Driving pressure', unit: 'cmH₂O', dec: 1, key: 'dp',
			in: [['vt', '+'], ['crs', '-']], range: { warnHi: 14, critHi: 18 },
			desc: 'VT rapportato alla compliance: è lo stress ciclico del polmone aerato. Associata alla mortalità nell’ARDS (obiettivo < 15).',
			formula: 'ΔP = Pplat − PEEPtot = VT/Crs' },
		{ id: 'overdist', cat: 'mech', col: 1, row: 7, label: 'Sovradistensione', unit: '%', dec: 0, key: 'overdist',
			in: [['pplat', '+'], ['recruit', '-']], range: { warnHi: 15, critHi: 40 },
			desc: 'Quanto il polmone aerato si avvicina alla capacità massima a fine inspirazione. Comprime i capillari alveolari: aumenta spazio morto e resistenze polmonari e devia il flusso verso le zone non aerate.',
			formula: 'riempimento = (V PEEP + VT)/Vmax aerato;  sovradistensione = (riempimento − 0,55)/0,35' },
		{ id: 'mpaw', cat: 'mech', col: 1, row: 8, label: 'Pressione media vie aeree', unit: 'cmH₂O', dec: 1, key: 'mpaw',
			in: [['peeptot', '+'], ['pplat', '+'], ['ti', '+'], ['rr', '+']],
			desc: 'Media della pressione nelle vie aeree sull’intero ciclo. È il principale determinante dell’ossigenazione e degli effetti emodinamici della ventilazione.',
			formula: 'mPaw = (1/Ttot)·∫ Paw dt  (dalla curva di pressione)' },
		{ id: 'mp', cat: 'mech', col: 1, row: 9, label: 'Potenza meccanica', unit: 'J/min', dec: 1, key: 'mp',
			in: [['rr', '+'], ['vt', '+'], ['dp', '+'], ['peeptot', '+']], range: { warnHi: 17, critHi: 25 },
			desc: 'Energia trasferita al polmone ogni minuto: sintetizza VT, frequenza, flusso e PEEP. Valori > 17 J/min sono associati a danno da ventilazione (VILI).',
			formula: 'MP = 0,098·FR·∫ Paw dV (fase inspiratoria)' },

		/* --------------------------------------------- lung volume & exchange */
		{ id: 'eelv', cat: 'mech', col: 2, row: 0, label: 'Volume di fine espirazione', unit: 'mL', dec: 0, key: 'eelv',
			in: [['peeptot', '+'], ['recruit', '+']],
			desc: 'EELV: capacità funzionale residua aerata + volume aggiunto dalla PEEP (reclutamento + distensione).',
			formula: 'EELV = 25 mL/kg·PBW·aerazione + V(PEEPtot)' },
		{ id: 'strain', cat: 'mech', col: 2, row: 1, label: 'Strain globale', unit: '', dec: 2, key: 'strain',
			in: [['vt', '+'], ['peeptot', '+'], ['recruit', '-']], range: { warnHi: 1.5, critHi: 2 },
			desc: 'Deformazione del polmone aerato a fine inspirazione: volume insufflato sopra la CFR (VT + volume da PEEP) rapportato alla CFR aerata. Valori > 1,5–2 sono lesivi (Chiumello 2008).',
			formula: 'strain = (VT + V_PEEP) / CFR aerata' },
		{ id: 'ppl', cat: 'mech', col: 2, row: 2, label: 'Pressione pleurica media', unit: 'cmH₂O', dec: 1, key: 'pplMean',
			subFn: o => (o.pplMeanMmHg).toFixed(1) + ' mmHg', in: [['mpaw', '+'], ['ccw', '-'], ['crs', '+'], ['iap', '+']],
			desc: 'È la pressione che circonda cuore e grandi vasi: il ponte tra ventilazione e circolazione. La frazione di Paw trasmessa è Ecw/(Ecw+EL): con polmone rigido (ARDS) se ne trasmette meno, con parete rigida (obesità, addome) di più.',
			formula: 'Ppl = Ppl₀ + V/Ccw − Pmus (sforzo inspiratorio)' },
		{ id: 'ptp', cat: 'mech', col: 2, row: 3, label: 'Stress transpolmonare', unit: 'cmH₂O', dec: 1, key: 'ptp',
			in: [['pplat', '+'], ['ppl', '-']], range: { warnHi: 20, critHi: 25 },
			desc: 'Pressione che distende realmente il polmone a fine inspirazione (Pplat − Ppl). È lo “stress” del polmone.',
			formula: 'PL = Pplat − Ppl(fine inspirazione)' },
		{ id: 'shunt', cat: 'gas', col: 2, row: 4, label: 'Shunt', unit: '%', dec: 0, key: 'shunt',
			in: [['recruit', '-'], ['overdist', '+'], ['co', '+']], range: { warnHi: 15, critHi: 30 },
			desc: 'Sangue che attraversa zone non ventilate senza ossigenarsi. Si riduce con il reclutamento; aumenta se la sovradistensione devia flusso verso le zone collassate, e con portate elevate (effetto Dantzker).',
			formula: 'Qs/Qt = 2% + 70%·(1 − aerazione)·(GC/GC₀)^0,35 + 15%·sovradistensione·(1 − aerazione) + 35%·shunt da patologia' },
		{ id: 'vdvt', cat: 'gas', col: 2, row: 5, label: 'Spazio morto (VD/VT)', unit: '%', dec: 0, key: 'vdvt',
			in: [['overdist', '+'], ['co', '-'], ['vt', '-']], range: { warnHi: 50, critHi: 65 },
			desc: 'Frazione del volume corrente che non partecipa agli scambi: anatomico (~2,2 mL/kg) + alveolare (zone ventilate ma poco perfuse: sovradistensione, bassa portata, microtrombosi).',
			formula: 'VD/VT = 1 − VA/(FR·VT)' },
		{ id: 'va', cat: 'gas', col: 2, row: 6, label: 'Ventilazione alveolare', unit: 'L/min', dec: 2, key: 'va',
			in: [['vt', '+'], ['rr', '+'], ['vdvt', '-']],
			desc: 'Ventilazione che raggiunge alveoli perfusi. Determina direttamente la PaCO₂.',
			formula: 'VA = FR·(VT − VDanat)·(1 − VDalv)' },
		{ id: 'paco2', cat: 'gas', col: 2, row: 7, label: 'PaCO₂', unit: 'mmHg', dec: 0, key: 'paco2',
			in: [['va', '-']], range: { warnLo: 32, critLo: 25, warnHi: 50, critHi: 65 },
			desc: 'Anidride carbonica arteriosa. Varia lentamente perché i depositi corporei di CO₂ sono ampi (minuti). In apnea (es. insufflazione sostenuta) sale di 5–10 mmHg/min.',
			formula: 'dPaCO₂/dt = (VCO₂ − VA·PaCO₂/0,863)/C_CO₂;  a regime PaCO₂ = 0,863·VCO₂/VA' },
		{ id: 'etco2', cat: 'gas', col: 2, row: 8, label: 'EtCO₂', unit: 'mmHg', dec: 0, key: 'etco2',
			in: [['paco2', '+'], ['vdvt', '-']], subFn: o => 'gap Pa−Et ' + (o.paco2 - o.etco2).toFixed(0),
			desc: 'CO₂ di fine espirazione. Il gradiente PaCO₂ − EtCO₂ aumenta con lo spazio morto alveolare: un calo improvviso di EtCO₂ dopo un aumento di PEEP può indicare calo di portata o sovradistensione.',
			formula: 'EtCO₂ ≈ PaCO₂·(1 − VDalv)' },
		{ id: 'pao2', cat: 'gas', col: 2, row: 9, label: 'PaO₂', unit: 'mmHg', dec: 0, key: 'pao2',
			in: [['fio2', '+'], ['va', '+'], ['shunt', '-'], ['svo2', '+'], ['paco2', '-']], range: { warnLo: 70, critLo: 55 },
			desc: 'Ossigeno arterioso: miscela del sangue capillare ossigenato con il sangue venoso misto dello shunt. Per questo dipende anche dalla SvO₂: se la gittata cala, il sangue venoso è più desaturato e la PaO₂ peggiora a parità di shunt. Il gas nel polmone è una riserva di O₂: se la ventilazione si ferma o crolla (apnea, perdita del circuito) la PAO₂ scende in pochi minuti, più in fretta con un polmone piccolo (ARDS, obesità).',
			formula: 'CaO₂ = (1 − Qs − Qlow)·Cc′O₂ + Qlow·C_lowV/Q + Qs·CvO₂;  dPAO₂/dt = [VA·(PIO₂ − PAO₂) − K·VO₂]/Vpolm' },
		{ id: 'spo2', cat: 'gas', col: 2, row: 10, label: 'SpO₂', unit: '%', dec: 0, key: 'spo2',
			in: [['pao2', '+']], range: { warnLo: 92, critLo: 88 },
			desc: 'Saturazione periferica (con ritardo del pulsossimetro ~8 s). Segue la PaO₂ lungo la curva di dissociazione dell’emoglobina.',
			formula: 'Severinghaus: S = 1 / (23400/(P³ + 150P) + 1)' },
		{ id: 'pf', cat: 'gas', col: 2, row: 11, label: 'P/F', unit: 'mmHg', dec: 0, key: 'pf',
			in: [['pao2', '+'], ['fio2', '-']], range: { warnLo: 300, critLo: 150 },
			desc: 'Rapporto PaO₂/FiO₂: classifica l’ARDS (lieve 200–300, moderata 100–200, grave < 100).',
			formula: 'P/F = PaO₂ / FiO₂' },

		/* --------------------------------------------- venous return & right heart */
		{ id: 'pmsf', cat: 'hemo', col: 3, row: 0, label: 'P. media di riempimento', unit: 'mmHg', dec: 1, key: 'pmsf',
			in: [['volemia', '+'], ['symp', '+'], ['ppl', '+']],
			desc: 'Pressione media sistemica di riempimento (Pmsf, Guyton): la “spinta” a monte del ritorno venoso. Aumenta con volemia e venocostrizione simpatica; la PEEP la aumenta un po’ comprimendo l’addome (compenso parziale).',
			formula: 'Pmsf = 12 + ΔVolemia/Cven + 3,5·simpatico + 0,3·ΔPpl' },
		{ id: 'rap', cat: 'hemo', col: 3, row: 1, label: 'PVC (P. atriale dx)', unit: 'mmHg', dec: 1, key: 'rap',
			in: [['ppl', '+'], ['pmsf', '+'], ['rvfunc', '-']], range: { warnHi: 12, critHi: 16 },
			desc: 'Pressione a valle del ritorno venoso. Con la ventilazione a pressione positiva sale perché aumenta la pressione pleurica attorno all’atrio, non perché aumenti il riempimento: la PVC sale mentre il precarico transmurale scende.',
			formula: 'Intersezione tra ritorno venoso (Pmsf − PVC)/RVR e curva di Starling f(PVC − Ppl)' },
		{ id: 'vrg', cat: 'hemo', col: 3, row: 2, label: 'Gradiente di ritorno venoso', unit: 'mmHg', dec: 1, key: 'vrGradient',
			in: [['pmsf', '+'], ['rap', '-']],
			desc: 'Differenza Pmsf − PVC che spinge il sangue verso il cuore destro: è il meccanismo principale con cui la PEEP riduce la gittata cardiaca.',
			formula: 'Ritorno venoso = (Pmsf − PVC) / RVR' },
		{ id: 'pvr', cat: 'hemo', col: 3, row: 3, label: 'Resistenze polmonari', unit: 'dyn·s·cm⁻⁵', dec: 0, key: 'pvrDyn',
			in: [['recruit', '±'], ['overdist', '+'], ['pao2', '-'], ['ph', '-']], range: { warnHi: 250, critHi: 400 },
			desc: 'Curva a U rispetto al volume polmonare: alte a bassi volumi (vasi extra-alveolari compressi e vasocostrizione ipossica nelle zone collassate), minime alla CFR, di nuovo alte con la sovradistensione (vasi alveolari schiacciati). Aumentano con ipossia e acidosi.',
			formula: 'PVR = PVR₀·f(collasso)·f(sovradistensione)·HPV·acidosi' },
		{ id: 'mpap', cat: 'hemo', col: 3, row: 4, label: 'PA polmonare media', unit: 'mmHg', dec: 0, key: 'mpap',
			in: [['pvr', '+'], ['co', '+'], ['mpaw', '+'], ['ppl', '+']], range: { warnHi: 25, critHi: 35 },
			desc: 'Pressione in arteria polmonare: è il postcarico del ventricolo destro. Dipende dalla pressione a valle del circolo polmonare: normalmente la pressione atriale sinistra (PAWP, che include la pressione pleurica), ma dove la pressione alveolare supera quella venosa (zone di West 1-2) i capillari si comportano come una cascata e a valle conta la pressione alveolare. Per questo PEEP alta e ipovolemia aumentano il postcarico del VD.',
			formula: 'mPAP = P valle + GC·PVR;  P valle = PAWP + eccesso alveolare (zone di West lungo ~14 mmHg di altezza idrostatica del polmone supino)' },
		{ id: 'rvfunc', cat: 'hemo', col: 3, row: 5, label: 'Funzione VD', unit: '%', dec: 0, key: 'rvFunc',
			in: [['mpap', '-'], ['ppl', '+'], ['sv', '+']], range: { warnLo: 85, critLo: 65 },
			desc: 'Accoppiamento ventricolo destro-arteria polmonare. Il postcarico del VD è l\u2019elastanza arteriosa Ea = pressione polmonare transmurale / gittata sistolica: a differenza della mPAP non cala quando cala il flusso, e non conta la pressione pleurica (circonda sia il VD sia l\u2019arteria). Quando Ees/Ea scende verso 1 il VD si disaccoppia: tipico di PEEP alta, zone di West e ipovolemia.',
			formula: 'Ea = (mPAP \u2212 Ppl) / GSi;  Ees/Ea \u2265 1,2 \u2192 100%, sotto cala fino a un minimo del 50%;  \u03c4 = 4 s' },
		{ id: 'ppv', cat: 'hemo', col: 3, row: 6, label: 'Variazione P. di polso', unit: '%', dec: 0, key: 'ppv',
			in: [['vt', '+'], ['ppl', '+'], ['volemia', '-']], range: { warnHi: 13, critHi: 20 },
			desc: 'PPV: oscillazione respiratoria della pressione di polso. Alta quando il cuore lavora sulla parte ripida della curva di Starling (precarico-dipendenza): predice la risposta ai fluidi, se VT ≥ 8 mL/kg e ritmo sinusale.',
			formula: 'PPV ≈ 2% + 10·ΔPpl tidalica (mmHg)·pendenza della curva di Starling / GC  (modello semplificato)' },
		{ id: 'lvtm', cat: 'hemo', col: 3, row: 7, label: 'Postcarico VS', unit: 'mmHg', dec: 0, key: 'lvTransmural',
			in: [['map', '+'], ['ppl', '-']],
			desc: 'Pressione sistolica transmurale del VS (PAS − Ppl). La pressione positiva la riduce: nello scompenso sistolico questo scarico del VS può aumentare la gittata.',
			formula: 'P transmurale VS = PAS − Ppl' },

		/* --------------------------------------------------- heart & systemic */
		{ id: 'symp', cat: 'hemo', col: 4, row: 0, label: 'Tono simpatico', unit: '%', dec: 0, key: 'symp',
			in: [['map', '-'], ['pao2', '-'], ['paco2', '+']],
			desc: 'Riflesso barocettivo (e chemocettivo): quando la pressione arteriosa scende aumentano frequenza, contrattilità, vasocostrizione arteriosa e venosa. Agisce in 10–20 s.',
			formula: 'simpatico → 5·(PAM₀ − PAM)/PAM₀ + chemoriflesso,  τ = 10 s' },
		{ id: 'hr', cat: 'hemo', col: 4, row: 1, label: 'Frequenza cardiaca', unit: 'bpm', dec: 0, key: 'hr',
			in: [['symp', '+']], range: { warnLo: 50, critLo: 40, warnHi: 110, critHi: 130 },
			desc: 'Sale per compensare il calo di pressione (riflesso barocettivo).',
			formula: 'FC = FC basale·(1 + 0,5·simpatico)' },
		{ id: 'co', cat: 'hemo', col: 4, row: 2, label: 'Gittata cardiaca', unit: 'L/min', dec: 2, key: 'co',
			subFn: o => 'IC ' + o.ci.toFixed(1) + ' L/min/m²', in: [['vrg', '+'], ['rvfunc', '+'], ['hr', '+'], ['contract', '+'], ['lvtm', '-']],
			range: { warnLo: 4, critLo: 3 },
			desc: 'Ritorno venoso e funzione cardiaca devono coincidere (modello di Guyton). La PEEP la riduce soprattutto riducendo il ritorno venoso (ipovolemia!) e aumentando il postcarico del VD; può aumentarla nello scompenso sinistro.',
			formula: 'GC = (Pmsf − PVC)/RVR = GCmax·(1 − e^(−(PVC − Ppl)/k))' },
		{ id: 'sv', cat: 'hemo', col: 4, row: 3, label: 'Gittata sistolica', unit: 'mL', dec: 0, key: 'sv',
			in: [['co', '+'], ['hr', '-']], range: { warnLo: 50, critLo: 35 },
			desc: 'Volume espulso a ogni battito.',
			formula: 'GS = GC / FC' },
		{ id: 'svr', cat: 'hemo', col: 4, row: 4, label: 'Resistenze sistemiche', unit: 'dyn·s·cm⁻⁵', dec: 0, key: 'svrDyn',
			in: [['symp', '+'], ['ph', '+']],
			desc: 'Tono arteriolare: aumenta con il simpatico, si riduce con l’acidosi grave.',
			formula: 'RVS = RVS₀·(1 + 0,4·simpatico)·f(pH)' },
		{ id: 'map', cat: 'hemo', col: 4, row: 5, label: 'Pressione arteriosa media', unit: 'mmHg', dec: 0, key: 'map',
			subFn: o => o.sbp.toFixed(0) + '/' + o.dbp.toFixed(0) + ' mmHg', in: [['co', '+'], ['svr', '+']],
			range: { warnLo: 65, critLo: 55, warnHi: 110 },
			desc: 'PA = GC × RVS (+ PVC). Il calo dopo un aumento di PEEP o durante un reclutamento viene in parte compensato dal riflesso barocettivo.',
			formula: 'PAM = GC·RVS + PVC;  PP = GS/C arteriosa' },

		/* --------------------------------------------- oxygen transport */
		{ id: 'hb', cat: 'o2', col: 5, row: 0, label: 'Emoglobina', unit: 'g/dL', dec: 1, key: 'hb',
			in: [['volemia', '-']], range: { warnLo: 9, critLo: 7 },
			desc: 'Trasportatore dell’ossigeno. Si riduce con anemia cronica ed emodiluizione da fluidi.',
			formula: 'Hb = Hb₀·(1 − fattore anemia)·diluizione' },
		{ id: 'cao2', cat: 'o2', col: 5, row: 1, label: 'Contenuto arterioso O₂', unit: 'mL/dL', dec: 1, key: 'cao2',
			in: [['spo2', '+'], ['hb', '+']], range: { warnLo: 15, critLo: 12 },
			desc: 'Ossigeno legato all’emoglobina + disciolto.',
			formula: 'CaO₂ = 1,34·Hb·SaO₂ + 0,003·PaO₂' },
		{ id: 'do2', cat: 'o2', col: 5, row: 2, label: 'Trasporto di O₂ (DO₂)', unit: 'mL/min', dec: 0, key: 'do2',
			subFn: o => 'DO₂I ' + o.do2i.toFixed(0) + ' mL/min/m²', in: [['co', '+'], ['cao2', '+']],
			range: { warnLo: 750, critLo: 550 },
			desc: 'La variabile che conta davvero: se la PEEP migliora la SpO₂ ma riduce di più la gittata, l’ossigeno consegnato ai tessuti diminuisce.',
			formula: 'DO₂ = GC·CaO₂·10' },
		{ id: 'vo2', cat: 'o2', col: 5, row: 3, label: 'Consumo di O₂ (VO₂)', unit: 'mL/min', dec: 0, key: 'vo2',
			in: [['symp', '+'], ['do2', '+']],
			desc: 'Dipende dal metabolismo basale (BasalMetabolicRate), dallo stress e dallo sforzo respiratorio. Diventa dipendente dalla DO₂ solo sotto la soglia critica.',
			formula: 'VO₂ = BMR/1440/4,83·(1 + 0,12·simpatico) + lavoro respiratorio' },
		{ id: 'svo2', cat: 'o2', col: 5, row: 4, label: 'SvO₂', unit: '%', dec: 0, key: 'svo2',
			subFn: o => 'estrazione ' + o.o2er.toFixed(0) + '%', in: [['do2', '+'], ['vo2', '-']],
			range: { warnLo: 65, critLo: 55 },
			desc: 'Saturazione venosa mista: bilancio tra consegna e consumo di O₂.',
			formula: 'CvO₂ = CaO₂ − VO₂/(10·GC)' },
		{ id: 'lactate', cat: 'o2', col: 5, row: 5, label: 'Lattato', unit: 'mmol/L', dec: 1, key: 'lactate',
			in: [['do2', '-'], ['map', '-']], range: { warnHi: 2, critHi: 4 },
			desc: 'Sale quando l’estrazione di O₂ supera ~45% o la perfusione è insufficiente (debito di ossigeno). Evolve in minuti.',
			formula: 'lattato → 1 + 18·(ER − 0,45) + 0,08·(60 − PAM),  τ = 4 min' },
		{ id: 'ph', cat: 'o2', col: 5, row: 6, label: 'pH arterioso', unit: '', dec: 2, key: 'ph',
			subFn: o => 'HCO₃⁻ ' + o.hco3.toFixed(0), in: [['paco2', '-'], ['lactate', '-']],
			range: { warnLo: 7.32, critLo: 7.2, warnHi: 7.48, critHi: 7.55 },
			desc: 'Acidosi respiratoria (ipercapnia permissiva) o metabolica (lattica). L’acidosi aumenta le resistenze polmonari e riduce il tono vascolare sistemico.',
			formula: 'pH = 6,1 + log₁₀(HCO₃⁻ / (0,03·PaCO₂))' }
	];

	//Simplified formulas: the idea behind each node in one line (shown with "Formule semplificate")
	const SIMPLE = {
		peep: 'PEEP = valore impostato', insp: 'VC: VT impostato · PC: Pinsp', rr: 'FR impostata (o spontanea se più alta)',
		ti: 'Te = 60/FR − Ti', fio2: 'PAO₂ ≈ FiO₂·713 − PaCO₂/0,8', raw: 'R ↑ broncospasmo, BPCO, ostruzione',
		ccw: 'Ccw ↓ con l’obesità', lungdz: 'reclutabile: 8% (anestesia) ↑ con ARDS e polmonite', volemia: 'volume circolante / normale',
		contract: 'contrattilità ↓ con disfunzione VS', iap: 'IAP ↑ → parete più rigida, Ppl ↑',
		vt: 'VC: VT = flusso × tempo · PC: VT ≈ ΔP × Crs', autopeep: 'PEEPi = V intrappolato / Crs',
		peeptot: 'PEEPtot = PEEP + PEEPi', recruit: 'si apre se Pplat > Papertura, resta aperto se PEEP > Pchiusura',
		crs: 'Crs = VT / (Pplat − PEEPtot)', pplat: 'Pplat = PEEPtot + VT / Crs', dp: 'ΔP = Pplat − PEEPtot = VT / Crs',
		overdist: '↑ quando il volume di fine insp. si avvicina al massimo', mpaw: 'Pmedia ≈ PEEP + (Ppicco − PEEP)·Ti/Ttot',
		mp: 'PM ≈ 0,098·FR·VT·(Ppicco − ΔP/2)', eelv: 'EELV = FRC aerata + volume da PEEP',
		strain: 'strain = (VT + V_PEEP) / FRC', ppl: 'Ppl = Ppl₀ + V / Ccw', ptp: 'PL = Pplat − Ppl',
		shunt: 'shunt ≈ polmone non aerato × perfusione', vdvt: 'VD/VT = 1 − VA / (FR·VT)', va: 'VA = FR · (VT − VD)',
		paco2: 'PaCO₂ = 0,863 · VCO₂ / VA', etco2: 'EtCO₂ ≈ PaCO₂ · (1 − VD alveolare)',
		pao2: 'CaO₂ = sangue ossigenato + sangue di shunt', spo2: 'SpO₂ = curva di dissociazione (PaO₂)', pf: 'P/F = PaO₂ / FiO₂',
		pmsf: 'Pmsf ↑ con volemia, simpatico, Ppl', rap: 'PVC dove ritorno venoso = gittata', vrg: 'RV = (Pmsf − PVC) / Rrv',
		pvr: 'PVR ↑ con atelettasia e sovradistensione', mpap: 'PAPm = Pvalle + GC × PVR', rvfunc: '↓ se il postcarico VD (Ea) supera la contrattilità (Ees)',
		ppv: 'PPV ∝ oscillazione Ppl × dipendenza dal precarico', lvtm: 'postcarico VS = PAS − Ppl',
		symp: '↑ se la PAM cala o con ipossia/ipercapnia', hr: 'FC = FCbase · (1 + 0,5 · simpatico)',
		co: 'GC = ritorno venoso = (Pmsf − PVC) / Rrv', sv: 'GS = GC / FC', svr: 'RVS ↑ simpatico, ↓ acidosi', map: 'PAM = GC × RVS + PVC',
		hb: 'Hb ↓ con anemia e diluizione', cao2: 'CaO₂ = 1,34·Hb·SaO₂ + 0,003·PaO₂', do2: 'DO₂ = GC × CaO₂ × 10',
		vo2: 'VO₂ = metabolismo (se DO₂ basta)', svo2: 'CvO₂ = CaO₂ − VO₂ / (GC·10)', lactate: '↑ se estrazione O₂ > 45% o PAM < 60',
		ph: 'pH = 6,1 + log(HCO₃⁻ / 0,03·PaCO₂)'
	};

	const byId = {};
	NODES.forEach(n => { byId[n.id] = n; n.out = []; n.simple = SIMPLE[n.id] || n.formula; });
	NODES.forEach(n => n.in.forEach(([src, sign]) => byId[src].out.push([n.id, sign])));

	function nodeValue(n, o) { return n.value ? n.value(o) : o[n.key]; }

	function nodeStatus(n, o) {
		const r = n.range;
		if (!r) return 'ok';
		const v = r.valueFn ? r.valueFn(o) : nodeValue(n, o);
		if ((r.critLo !== undefined && v < r.critLo) || (r.critHi !== undefined && v > r.critHi)) return 'crit';
		if ((r.warnLo !== undefined && v < r.warnLo) || (r.warnHi !== undefined && v > r.warnHi)) return 'warn';
		return 'ok';
	}

	global.BreatheNodes = { CATEGORIES, NODES, byId, nodeValue, nodeStatus };
})(typeof window !== 'undefined' ? window : globalThis);
